# Generated by Django 5.0.5 on 2024-10-22 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='description',
        ),
        migrations.RemoveField(
            model_name='collegeprogram',
            name='course_coordinator',
        ),
        migrations.RemoveField(
            model_name='collegeprogram',
            name='enrollment_season',
        ),
        migrations.RemoveField(
            model_name='collegeprogram',
            name='title',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='faculty_name',
        ),
        migrations.AddField(
            model_name='collegeprogram',
            name='program',
            field=models.CharField(choices=[('Business Program', 'Business Program'), ('Hospitality Program', 'Hospitality Program'), ('Digital Marketing', 'Digital Marketing'), ('Health Care Program', 'Health Care Program'), ('Community Programs', 'Community Programs'), ('Education Assist', 'Education Assist')], default='Business Program', max_length=200),
        ),
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='course_management.branch'),
        ),
    ]
