# Generated by Django 5.0.5 on 2024-10-22 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0002_remove_branch_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeprogram',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='collegeprogram',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='course_management.branch'),
        ),
    ]
