# Generated by Django 5.0.5 on 2024-10-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0005_alter_collegeprogram_enrollment_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeprogram',
            name='enrollment_term',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], default='Spring', max_length=20),
        ),
        migrations.AlterField(
            model_name='collegeprogram',
            name='program',
            field=models.CharField(choices=[('Business Program', 'Business Program'), ('Hospitality Program', 'Hospitality Program'), ('Digital Marketing', 'Digital Marketing'), ('Health Care Program', 'Health Care Program'), ('Community Programs', 'Community Programs'), ('Education Assist', 'Education Assist')], default='Business Program', max_length=200),
        ),
    ]
