# Generated by Django 5.0.5 on 2024-11-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0006_alter_collegeprogram_enrollment_term_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeprogram',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='collegeprogram',
            name='start_date',
        ),
        migrations.AddField(
            model_name='collegeprogram',
            name='dates',
            field=models.TextField(default=1),
        ),
    ]
