# Generated by Django 5.0.5 on 2024-11-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_management', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
